const Discord = require("discord.js");

module.exports = async (menu) => {      
  menu.reply.think(true);

  if (menu.values[0] === 'yay') {
      await menu.clicker.member.roles.add(conf.roles.yay)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.yay+"> rolü üzerinize verildi.")

}
  if (menu.values[0] === 'oğlak') {
      await menu.clicker.member.roles.add(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.oglak+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'kova') {
      await menu.clicker.member.roles.add(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.kova+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'balık') {
      await menu.clicker.member.roles.add(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.balik+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'aslan') {
      await menu.clicker.member.roles.add(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.aslan+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'başak') {
      await menu.clicker.member.roles.add(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.basak+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'terazi') {
      await menu.clicker.member.roles.add(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.terazi+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'akrep') {
      await menu.clicker.member.roles.add(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.akrep+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'koç') {
      await menu.clicker.member.roles.add(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.koc+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'boğa') {
      await menu.clicker.member.roles.add(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.boga+"> rolü üzerinize verildi.")
}
  if (menu.values[0] === 'yengeç') {
      await menu.clicker.member.roles.add(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.yengec+"> rolü üzerinize verildi.")
  
}
  if (menu.values[0] === 'ikizler') {
      await menu.clicker.member.roles.add(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
      menu.reply.edit(":tada: Başarıyla <@&"+conf.roles.ikizler+"> rolü üzerinize verildi.")
}
    if (menu.values[0] === 'burctemizle') {
      await menu.clicker.member.roles.remove(conf.roles.ikizler)
      await menu.clicker.member.roles.remove(conf.roles.yengec)
      await menu.clicker.member.roles.remove(conf.roles.boga)
      await menu.clicker.member.roles.remove(conf.roles.koc)
      await menu.clicker.member.roles.remove(conf.roles.akrep)
      await menu.clicker.member.roles.remove(conf.roles.terazi)
      await menu.clicker.member.roles.remove(conf.roles.basak)
      await menu.clicker.member.roles.remove(conf.roles.aslan)
      await menu.clicker.member.roles.remove(conf.roles.balik)
      await menu.clicker.member.roles.remove(conf.roles.kova)
      await menu.clicker.member.roles.remove(conf.roles.oglak)
      await menu.clicker.member.roles.remove(conf.roles.yay)
        menu.reply.edit(":tada: Başarıyla üzerinizdeki burç rolleri temizlendi")
}
   }; 
module.exports.config = {
    name: "clickMenu"
  }